# Generated by Django 5.0.6 on 2024-06-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stack_project_content_alter_tag_name_project_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_img',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_project', to='main.projectimage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.ManyToManyField(blank=True, related_name='projects', to='main.stack'),
        ),
    ]
