
services:
  django_gunicorn:
    build:
      context: .
    restart: always
    volumes:
      - static:/static
      - data:/app/portfolio/
      - media:/app/portfolio/media
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file:
      - .env
      # target: runtime
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./docker/nginx
    restart: always
    env_file:
      - .env
    depends_on:
      - django_gunicorn
    volumes:
      - static:/static
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  certbot:
    build:
      context: ./docker/certbot
    command: echo "Skipping..."
    env_file:
      - .env
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - nginx
  
volumes:
  static:
  data:
  media:
  certbot-web:
  proxy-dhparams:
  certbot-certs: