
services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
      target: runtime
    ports:
      - "8000:8000"
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static: