# Generated by Django 5.0.6 on 2024-08-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_github_user_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_picture',
            field=models.ImageField(blank=True, null=True, upload_to='about_picture/'),
        ),
    ]
